name: 'Get Worker Name'
description: 'Extracts worker name from wrangler.toml and optionally appends suffix'

inputs:
  wrangler-toml-path:
    description: 'Path to wrangler.toml file'
    required: false
    default: 'packages/api/wrangler.toml'
  suffix:
    description: 'Optional suffix to append to worker name (e.g., -dev)'
    required: false
    default: ''

outputs:
  name:
    description: 'The worker name'
    value: ${{ steps.get-name.outputs.name }}

runs:
  using: 'composite'
  steps:
    - name: Get worker name
      id: get-name
      shell: bash
      run: |
        BASE_NAME=$(grep -m 1 '^name =' ${{ inputs.wrangler-toml-path }} | cut -d'"' -f2)
        WORKER_NAME="${BASE_NAME}${{ inputs.suffix }}"
        echo "name=$WORKER_NAME" >> $GITHUB_OUTPUT
        echo "WORKER_NAME=$WORKER_NAME" >> $GITHUB_ENV
        echo "Worker name: $WORKER_NAME"

